<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Clinic reports | Sunrise Dental Clinic</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/app.css"></head>
<body><div class="app-shell"><%@ include file="../fragments/sidebar.jspf" %><div class="workspace"><%@ include file="../fragments/topbar.jspf" %>
<main id="main-content" class="content"><h1 class="page-title">Clinic reports</h1>
<c:if test="${not empty success}"><div class="message message-success" role="status"><c:out value="${success}"/></div></c:if>
<c:if test="${not empty error}"><div class="message message-error" role="alert"><c:out value="${error}"/></div></c:if>

<section class="card"><h2>Daily appointment schedule</h2><form class="filter-row" method="get"><div class="form-group"><label for="date">Schedule date</label><input class="form-control" type="date" name="date" id="date" value="<c:out value='${reportDate}'/>" required></div><input type="hidden" name="from" value="<c:out value='${reportFrom}'/>"><input type="hidden" name="to" value="<c:out value='${reportTo}'/>"><button class="button button-primary">View schedule</button></form>
<div class="stats-grid"><div><h3><c:out value="${schedule.total}"/> appointments</h3><p><c:out value="${schedule.completed}"/> completed · <c:out value="${schedule.cancelled}"/> cancelled</p></div><div><h3>Most booked treatment</h3><p><c:out value="${schedule.popularTreatment}"/></p></div></div>
<div class="table-wrap"><table><caption>Visits in Sri Lanka time</caption><thead><tr><th>Number</th><th>Time</th><th>Patient</th><th>Dentist</th><th>Treatment</th><th>Status</th></tr></thead><tbody><c:forEach items="${schedule.appointments}" var="a"><tr><td><c:out value="${a.appointmentNumber}"/></td><td><c:out value="${a.time}"/></td><td><c:out value="${a.patientName}"/></td><td><c:out value="${a.dentistName}"/></td><td><c:out value="${a.treatmentName}"/></td><td><span class="badge"><c:out value="${a.status}"/></span></td></tr></c:forEach><c:if test="${empty schedule.appointments}"><tr><td colspan="6">No appointments on this date.</td></tr></c:if></tbody></table></div></section>
<section class="card"><h2>Revenue / billing summary</h2><p>Issued bill totals, including legacy discounts. This is not a payment collection report.</p>
<form class="filter-row" method="get"><input type="hidden" name="date" value="<c:out value='${reportDate}'/>"><div class="form-group"><label for="from">From date</label><input class="form-control" type="date" id="from" name="from" value="<c:out value='${reportFrom}'/>" required></div><div class="form-group"><label for="to">To date (inclusive)</label><input class="form-control" type="date" id="to" name="to" value="<c:out value='${reportTo}'/>" required></div><button class="button button-primary">View summary</button></form>
<dl class="details-grid"><div><dt>Number of bills</dt><dd><c:out value="${revenue.billCount}"/></dd></div><div><dt>Treatment revenue (LKR)</dt><dd><c:out value="${revenue.treatmentRevenue}"/></dd></div><div><dt>Consultation fees (LKR)</dt><dd><c:out value="${revenue.consultationRevenue}"/></dd></div><div><dt>Discounts (LKR)</dt><dd><c:out value="${revenue.discounts}"/></dd></div><div><dt>Total billed revenue (LKR)</dt><dd><strong><c:out value="${revenue.totalRevenue}"/></strong></dd></div></dl></section>
</main></div></div></body></html>
